Qbox-project/qbx_vehiclekeys

client/main.lua
fxmanifest.lua
server/main.lua

Converted all the notifys, progress bars n stuff to ox_lib shit

Convert ProgressBars, Notifys

---

locales/cs.lua

Add cs.lua

---

locales/de.lua

chore(locales): update de.lua

---

client/main.lua
fxmanifest.lua
server/main.lua

tweak: adjust to new core changes

---

client/main.lua
server/main.lua

I guess we missed to convert the notify trigger serverside.

Adapt notify export on serverside

---

client/functions.lua
server/functions.lua

Implementation include HasKey(), GiveKey(), RemoveKey(), SetDoorState(), ToggleDoorState()

[WIP] Server side function implementation

---

client/main.lua

fix: Should be a fix for the alarm constantly going off at times as well as at the wrong time
feat: Exports for locking and unlocking the door with effects.

Alarm & Export update

---

client/functions.lua
client/main.lua
fxmanifest.lua
locales/cs.json
locales/de.json
locales/en.json
locales/es.json
locales/et.json
locales/fr.json
locales/nl.json
locales/pt.json
locales/ro.json
server/commands.lua
server/functions.lua
server/main.lua

Fixes:
- Givekeys distance not being the same in 2 different places
- Being able to drive when you don't have the keys for the first 2 seconds of the loop
- Locking mechanism triggering on parked player owned cars when it only needs to be on npc cars
- Command incosistensies

Fixes small issues

---

client/functions.lua
client/main.lua
config/client.lua

simplified function areKeysJobShared

feat: refactor of the areKeysJobShared 

---

server/functions.lua

redundant vehicle data has been loaded

feat: select only plate in addPlayer

---

client/main.lua

Mapping in getOtherPlayersInVehicle makes more sense

feat: serverIds in getOtherPlayersInVehicle

---

server/commands.lua

feat: optional playerId of givekeys command

---

client/functions.lua
client/main.lua
config/client.lua
config/shared.lua
fxmanifest.lua
shared/functions.lua

To improve the door closing mechanism the functions should also be available from the server.
In addition, the prefix "is" should be reserved for variables.

feat(shared): move getIsVehicleBlacklisted and getIsVehicleImmune to shared

---

client/main.lua

Fixes lock toggle when in a vehicle.

fix(client): getVehicle when in vehicle

---

client/functions.lua
client/main.lua
config/client.lua
config/shared.lua
shared/functions.lua

Moving isBlacklistedWeapon to shared.

feat(shared): getIsBlacklistedWeapon

---

locales/da.json

feat(locales): danish translation

Create da.json (#73)

---

client/main.lua
locales/cs.json
locales/de.json
locales/en.json
locales/es.json
locales/et.json
locales/fr.json
locales/nl.json
locales/pt.json
locales/ro.json
locales/tr.json

The name "search_keys" can be used  as a description of the button bind.

refactor(locale): search_keys to search_keys_dispatch

---

client/main.lua
config/client.lua
config/shared.lua
shared/functions.lua

unifies the mechanism of the shared functions and adds some additional

feat(shared/functions): shared function unification

---

client/commands.lua
client/functions.lua
client/main.lua

separating command-related functions from the rest of the code will improve code readability

refactor(client/commands): qb-vehiclekeys:client:GiveKeys to separate file

---

config/client.lua

chore(client/config): remove debug flag

---

client/commands.lua
server/main.lua

feat(merge): main to renew

---

config/server.lua
server/main.lua

Simplify the configuration, and increase the configurability of closing the doors of new vehicles

feat(server/lockDoors): lockNPCCars chance config parameters

---

client/main.lua

fix(VehicleInfo): validation

---

client/main.lua

fix(client/carjack): progressActive before cancelProgress

---

client/functions.lua
client/main.lua

refactor(client): rename attemptPoliceAlert to sendPoliceAlertAttempt

---

client/functions.lua
client/main.lua

refactor(client): move functions

---

fxmanifest.lua

The section will not be needed

chore(fxmanifest): remove dependencies section

---

client/functions.lua
client/main.lua
locales/da.json
server/functions.lua

support shared function  in toggleEngine and getIsVehicleAlwaysUnlocked

feat: toggleEngine and getIsVehicleAlwaysUnlocked

---

client/functions.lua
config/client.lua

- made enums local variables and made their names singular
- added type annotations to tables
- lowercased local variables
- made skill check config two named keys for difficulty and inputs instead of a two element array
Part of #91

refactor(config/client): added types

---

client/functions.lua

removed an obsolete condition that broke lockpicking and hotwiring

fix(lockpickDoor/hotwire): config verification

---

client/main.lua

hiding the search keys message when the keys are found.

fix(searchKeys): label

---

client/main.lua

fix(toggleEngine): disable

---

client/main.lua

Changed audio to a keyfob sound

feat(audio): changed key sound

---

config/shared.lua

Bikes should be open by default

chore(config): no lock bikes

---

client/main.lua
config/client.lua

configurable keeping the engine running

feat(showHotwiringLabel): keeps engine on when config

---

client/carjack.lua
client/functions.lua
client/main.lua
fxmanifest.lua

refactor(client): extract carjack code into its own file

---

client/main.lua

- Renamed showHotwiringLabel to onEnteringDriverSeat as this function does more than just the search keys enabling
- refactored more out of the thread, so that the thread only contains disabling the engine and actions to take when the player acquires keys (cancelling a progress bar if the user if one is in progress & disabling searching for keys)
- Removed triggers related to vehicle cache. seat cache is more specific and less confusing to reason about.
- Flattened code and used more guard clauses
- added debug prints

refactor(client/main): onEnteringDriverSeat event

---

bridge/qb/client.lua
bridge/qb/server.lua
bridge/qb/shared.lua
client/functions.lua
client/main.lua
server/keys.lua

- HasKeys returns a boolean instead of boolean?
- HasKeys client param optional, defaults to current vehicle
- fixed HasKeys client bridge function
- Prevent searching for keys animation being interrupted while progress bar is in progress

fix: compat fixes

---

locales/ja.json

- I added japanese translation.

chore: add new locale [ ja ]

---

server/main.lua

New server-side export to lock/unlock vehicles. Used in my pr for full persistence.

feat(server/main): new SetVehLockState export

---

config/client.lua

Update config client.lua comment

---

locales/en.json
server/commands.lua

related to this pr https://github.com/Qbox-project/qbx_core/pull/689

feat: add opt-in check
