- client/main.lua
don't allow to move vehicle while progress bar active
> fix(client/main): don't allow to move vehicle while progress bar active

- client/main.lua
- fxmanifest.lua
- server/main.lua
Adds the modules, replaces the deprecated export and functions, further use of cache.vehicle, and then some minor style fixes
> refactor: move to modules, more ox_lib, style fixes

- fxmanifest.lua
- server/main.lua
removes nonexistent module so script doesn't warn on startup.
fixed https://github.com/Qbox-project/qbx_vehiclekeys/issues/15 attempt to index a nil value (global 'QBX')
> chore: nonexistent module -Axxu

- client/main.lua
- server/main.lua
Fixes errors and uses imported utils, rather then calling QBX.Functions, Removes depreciated Player.RemoveItem call
As a side note #4 indicates you are looking to replace this script. I have a custom vehiclekeys script from when I was working on NRRP that I'd be happy to share. Its not 100%, but it would be a start
> 🐛 Replace QBX.Functions calls, depreciated RemoveItem

- server/main.lua
Adds an export to allow the server side to Give keys
necessary to fix /car in [qbx_core #205](https://github.com/Qbox-project/qbx_core/pull/205)
> GiveKeys export

- client/main.lua
- config.lua
There was a typo in the config for the removal of the lockpick, so I fixed it and also updated the advanced one to match the normal lockpick name
> fix: typos in config and client main

- client/main.lua
Variable in the configuration is lockNPCDrivenCars not lockNPCDrivingCars. This fixes the typo allowing NPC driven vehicles to be locked as desired.
> fix: config variable typo

- client/main.lua
Fix car jacking typos to make car jackings work again
This fixes typos related to car jacking and the actual config name. As well as fixing the timers due to typos
> Fix car jacking

- client/functions.lua
- client/main.lua
- config/client.lua
- fxmanifest.lua
- locales/en.json
- server/commands.lua
- server/main.lua
- shared/functions.lua
**Major changes**
Change the data structure of vehicleKeys[plate][citizenid] to keysList[citizenid][plate]. This simplifies the logic of most functions.
Instead of synchronizing the variable on the client side, the player's statebag is modified.
Vehicle spawning works in shops, fixed GetKeys function
**Other changes**
fixed lint tests by rewriting imports
lockpicking for all vehicle doors
restored oryginal qbx fxmanifest.lua style
Need to think about how you can optimize the storage of keys in a variable on the server
> fix: Garage vehicles spawn feat: statebag of keys

- client/functions.lua
- client/main.lua
- config/client.lua
- server/functions.lua
- server/main.lua
The main goal of MR is hotwiring with lockpick.
Moreover, GiveVehicleKeys notifications have been moved to the client side script, for the client's language support.
In addition, lockpicking of some vehicle classes with a standard lockpick has been blocked (If it is unnecessary, it can be easily dumped).
> feat: hotwiring with lockpick

- client/functions.lua
- client/main.lua
A thread that did 3 things at once was broken up into:
* QBCore:Client:VehicleInfo event
* ox_lib:cache:vehicle event
* carjacking thread
> The logic of carjacking needs to be improved.
> feat: break up client thread

- client/functions.lua
- client/main.lua
- config/client.lua
- config/server.lua
- server/main.lua
- shared/functions.lua
Each newly created vehicle has its initial lock status set. This is a one-time action for each vehicle.
> feat(server): init locks statuses

- client/commands.lua
Checking whether a player has keys is checked in too many parts of the code.
> feat(qb-vehiclekeys:client:GiveKeys): remove redundant has keys checking

- server/main.lua
Fixes the lock state when the vehicle lock is disabled
> fix(server/onEntityCreated): init lock state

- client/main.lua
Previously, this was causing a nil exception
> fix(client/main): default auto lock to false if job not in config

- client/functions.lua
- client/main.lua
- config/shared.lua
- server/main.lua
- shared/functions.lua
- types.lua
- Combined getIsVehicleAlwaysUnlocked & getIsVehicleTypeAlwaysUnlocked into one function, which also checks the state bag for ignoreLocks.
- Combined config for noLockVehicles and noLockVehicleTypes as sub-fields to make them visually closer together and linked.
- Added types field to lockedVehicles in config as a feature
- No longer using getIsVehicleLockpickImmune to mean that the vehicle should spawn locked. This behavior seemed like a side-effect, as one wouldn't assume that a vehicle that couldn't be lock picked was locked.
- Created types.lua meta file for containing typed annotations
> refactor: default locked state

- client/main.lua
- Extracted some functions to break up large ones
- renamed some variables for clarity
- changed negative condition to the positive case to make it clearer
> refactor(client/main): carjacking readability improvements

- config/shared.lua
- shared/functions.lua
- types.lua
Currently, the config is split up as a bunch of lists of vehicles that apply to each property. This can be confusing and difficult to reason about the properties that apply to each vehicle. Additionally, this structure allows conflicting properties to be applied to the same vehicle such as no lock and spawned locked.
This PR introduces a new config structure, which is an inversion of the current one. Vehicles are now the top level key, and a list of properties and config options pertaining to that vehicle are the value. This makes the config behavior per vehicle. Aside from directly configuring individual models, this structure also allows for configuring vehicle types and specifying a default for all vehicles. This inherits, meaning that for any given property field, the model's property …
> refactor: vehicles config

- client/functions.lua
- client/main.lua
- config/client.lua
- config/shared.lua
- shared/functions.lua
- types.lua
Since VehicleClass is only accessible from the client, we'll use the vehicle's category from core config instead to apply vehicle config on. With this we'll also be moving config currently in client to shared to have the vehicle specific config in one place to make it clearer.
Also fixes a bug which was not checking for empty config tables
> refactor: vehicle config by category and moving things to shared config

- config/client.lua
classes aggregating skillcheck and animations settings
> chore(client/config): entities classes

- client/main.lua
Prevents animation error when no keys.
> feat(hotwiring): disable INPUT_VEH_ACCELERATE when no keys

- config/server.lua
- config/shared.lua
- server/main.lua
- shared/functions.lua
- types.lua
Chance to lock a vehicle parked and driven by an npc.
> feat(getIsVehicleInitiallyLocked): integrate with lockNPCCarsChance

- client/main.lua
This fixes an issue where the search keys text UI would display when outside the vehicle, and the cooldown could be bypassed early resulting in multiple progress bars at the same time.
Repro steps:
1. Search for keys
2. Fail the search and immediately get out
3. Get back in to bypass the cooldown and start searching for keys again or stay outside and observe the text UI would pop up again even though the player is now outside the vehicle
> fix: allow searching keys only when in drivers seat and prevent bypassing cooldown

- shared/functions.lua
Passes a model hash instead of a vehicle ID to the server-side `GetVehicleClass` since that's what it accepts.
Blocked by Qbox-project/qbx_core#571.
> fix(shared/functions): pass model hash to `GetVehicleClass` export

- client/functions.lua
- client/main.lua
- config/client.lua
- config/shared.lua
- locales/cs.json
- locales/da.json
- locales/de.json
- locales/en.json
- locales/es.json
- locales/et.json
- locales/fr.json
- locales/nl.json
- locales/pt.json
- locales/ro.json
- locales/tr.json
- server/main.lua
When finishing lockpicking sometimes it is confusing if you miss the success message, now it will tel you it is already unlocked.
Added statebaghandler vehicle doorlocks state for better redundancy as the server-sided native is sometimes unreliable.
> fix: correct lockpick anim, notify when unlocked, added statebaghandler for doorlocks

- client/functions.lua
Observed an error executing IsEntityAVehicle function. Suspect it is due to a nil entity value, so adding this check.
> fix(client/functions): guard against vehicle not existing during raycast

- client/main.lua
- server/main.lua
This adds a check that someone isn't trying to toggle the locks of a vehicle without locks.
> fix: don't allow locking a vehicle without a lock

- client/functions.lua
Resolves an issue caused when a vehicle is spawned and then the plate is changed.
Essentially when a vehicle is initiailly spawned and the hotwire check is ran, the original vehicles plate is passed, however if the plate is updated by an external resource such as a personal vehicle from a garage, it doesn't process this always showing as no key access.
> fix: apply correct plate in access if changed after spawn

- client/main.lua
It's a better experience for players to do a distance check so they can get out of the car and lock the vehicle rather than turn around and make sure they face the vehicle first.
> feat: toggle locks via distance check rather than raycast

- client/carjack.lua
- client/functions.lua
- client/main.lua
- config/client.lua
- config/server.lua
- server/keys.lua
- server/main.lua
Want to move towards a world where we only modify vehicle keys on the server for security purposes.
This PR removes the acquire vehicle keys event and changes all the internal callers to use other means such as callbacks, or more specific events.
> refactor: remove acquirevehiclekeys event

- bridge/qb/client.lua
- bridge/qb/server.lua
- bridge/qb/shared.lua
- client/functions.lua
- fxmanifest.lua
- server/commands.lua
- server/keys.lua
This PR adds backwards compatibility with qb-vehiclekeys events and exports to Give, Remove, & check if a player has keys to a certain vehicle plate. This is done by searching through the vehicles to find the vehicles with the matching plate and then invoking native qbx_vehiclekeys functions to handle the rest. This means that if multiple vehicles have the same plate, these compatibility functions will operate on all of them. The bridge can be enabled/disabled via convar.
Other misc refactors done as part of this PR to support the bridge:
- made fxmanifest files more specific
- made client HasKeys a global function
- renamed server/keys.lua keysList and keysLifeTime to better reflect their use
- moved server HasKeys to keys.lua
- added some early return conditions in keys.lua
> feat: qb-vehiclekeys bridge

- client/carjack.lua
- client/functions.lua
- client/main.lua
- fxmanifest.lua
This makes it easier to refactor and split off feature based files. functions.lua is too broad and became a dumping ground.
Also deleted raycasting, which was not being used.
> refactor(client): use global functions instead of modules

- client/main.lua
Was able to reproduce a state where the statebag value would not match the client's setting for the vehicle lock state by having two clients both unlocking/locking the same vehicle at the same time. This resulted in a deadlock, where the native state was locked, but the statebag was set to locked, so the client attempted to toggle the state to locked. Since the state was already locked, this resulted in a no-op and the vehicle could not be unlocked.
This PR fixes this issue by checking on the client if the statebag is out of sync with the native and correcting the client to be set to the statebag before doing toggle logic. This is done when the client toggles the locks of the vehicle.
> fix: vehicle becoming permanently locked

- bridge/qb/server.lua
- server/keys.lua
When giving keys via the bridge (by plate) many vehicles match to the plate, so many keys are given and the notifications per vehicle spam the player. This changes the bridge to only show one notification even if keys are given to many vehicles.
- Adds a skipNotification optional field to RemoveKeys and GiveKeys
- Bridge handles its own notifications
> fix: notify spam

- bridge/qb/shared.lua
- client/functions.lua
- client/main.lua
- client/searchkeys.lua
- config/client.lua
- bridge: fixes an issue where clients would spawn vehicles and immediately give them keys via the plate. Since the vehicle entity isn't known to the server at the time the client gives keys to the plate, the client is never given keys to the expected vehicle. Added a 500ms delay to give time for the server to receive the entity from the client. Also checking for both the untrimmed and trimmed plates just in case to avoid missing an expected vehicle entity.
- supporting selecting shared job vehicles via class instead of just model
- send police alert function moved to client config as this will often be replaced by an export to a dispatch resource. There's a good argument to be made that we shouldn't even provide a default implementation since most servers won't use it. (Potential future …
> fix: miscl fixes

- client/main.lua
- server/main.lua
Instead of initializing vehicle lock state using entityCreated server event, which has a high performance cost, this PR determines the vehicle lock state of NPC vehicles on demand. Clients listen every 100ms for an attempt to enter a vehicle, randomize its lock state based on the config, and then set the state bag so that lock state is synced to other players.
> feat: on demand vehicle lock init

- README.md
Rewriting, adding all the features
> chore(README): re-write with more features

- bridge/qb/server.lua
In qbx_vehiclekeys, we assign keys to a specific vehicle entity rather than a plate. When using native qbx_vehiclekeys exports, the caller passes the entity to assign keys to. However, if using the bridge, we look up all vehicles with the given plate, which normally matches to like 30 vehicles, so it causes heavy performance usage setting statebag on all of those.
This PR fixes the issue by adding a 20ms delay between state bag sets to avoid overload.
> fix(bridge): statebag spam

- config/server.lua
- server/commands.lua
When attempting to hand keys to someone standing next to you without using an ID an error would be generated: 
The error was from a nil value. I added a config setting, got rid of the nil value error, and added in user notifications.
Before: https://medal.tv/games/gta-v/clips/je2GVr3kBS0OLfjWB?invite=cr-MSxsZ3csMTk1NzEzNDc0LA
After: https://medal.tv/games/gta-v/clips/je2JXUH9ehD7sHQ5P?invite=cr-MSxPYUMsMTk1NzEzNDc0LA
> fix: Resolve an error when giving keys without ID

- client/main.lua
Adds a feature to keep the vehicle engine running when it's abandoned. This ensures that the engine stays on based on the `keepEngineOnWhenAbandoned` setting in the configuration.
> feat(client/main): add vehicle engine keep-alive functionality when abandoned

- README.md
The README has been updated to include the new lock‑pick items and a short usage example.
- Added a **Lockpick** and **Advanced Lockpick** entry in the “Items” table.
- Provided a code snippet showing how to require the items (wrapped in a `return { … }` block) and how to call the client event.
- Fixed a few minor markdown issues (typos, broken links, heading levels) and refreshed the screenshot.
- Keeps the documentation in sync with the latest inventory definitions, preventing confusion for new contributors.
- Improves onboarding: anyone reading the README now sees exactly how to add or use lock‑pick items.
- No functional code changes, so it can be merged quickly.
Closes #\<issue‑number>  
--- 
*Optional (only if your repo runs CI on docs):*
---
1. **Create the commit** with the …
> docs(readme): update README with lockpick & advanced lockpick examples
